# TCL File Generated by Component Editor 13.0sp1
# Fri Feb 26 15:40:23 GMT 2016
# DO NOT MODIFY


# 
# DSD_COS_IN "DSD_COS_IN" v1.0
#  2016.02.26.15:40:23
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module DSD_COS_IN
# 
set_module_property DESCRIPTION ""
set_module_property NAME DSD_COS_IN
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP DSD
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME DSD_COS_IN
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL floor_div_4_sub_32
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file floor_div_4_sub_32.vhd VHDL PATH ../floor_div_4_sub_32.vhd TOP_LEVEL_FILE
add_fileset_file slv_shift.vhdl VHDL PATH ../slv_shift.vhdl


# 
# parameters
# 


# 
# display items
# 


# 
# connection point nios_custom_instruction_slave
# 
add_interface nios_custom_instruction_slave nios_custom_instruction end
set_interface_property nios_custom_instruction_slave clockCycle 0
set_interface_property nios_custom_instruction_slave operands 1
set_interface_property nios_custom_instruction_slave ENABLED true
set_interface_property nios_custom_instruction_slave EXPORT_OF ""
set_interface_property nios_custom_instruction_slave PORT_NAME_MAP ""
set_interface_property nios_custom_instruction_slave SVD_ADDRESS_GROUP ""

add_interface_port nios_custom_instruction_slave din dataa Input 32
add_interface_port nios_custom_instruction_slave dout result Output 32

